# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 900, 700))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 200, 201, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 150, 151, 61))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 240, 151, 61))
        self.pushButton_3.setObjectName("pushButton_3")
        self.volumeSlider = QtWidgets.QSlider(self.centralwidget)
        self.volumeSlider.setGeometry(QtCore.QRect(10, 30, 160, 31))
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName("volumeSlider")
        self.key_of_shif = QtWidgets.QLineEdit(self.centralwidget)
        self.key_of_shif.setGeometry(QtCore.QRect(20, 480, 113, 31))
        self.key_of_shif.setObjectName("key_of_shif")
        self.input_key = QtWidgets.QPushButton(self.centralwidget)
        self.input_key.setGeometry(QtCore.QRect(140, 480, 81, 31))
        self.input_key.setObjectName("input_key")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 450, 201, 31))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(190, 20, 601, 121))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(190, 300, 601, 121))
        self.lineEdit_2.setObjectName("lineEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Конвертировать"))
        self.pushButton.setText(_translate("MainWindow", "Шифровать"))
        self.pushButton_3.setText(_translate("MainWindow", "Расшифровать"))
        self.input_key.setText(_translate("MainWindow", "ввод ключа"))
        self.label.setText(_translate("MainWindow", "Ключ шифрования"))
